# Generated by Django 3.2.5 on 2021-07-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210705_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='person',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.user'),
        ),
    ]
