# Generated by Django 3.2.5 on 2021-07-05 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Product',
        ),
    ]
